---
name: Create and publish a Docker image

on:
  push:
    branches:
      - 'develop'
    tags-ignore:
      - '**'

env:
  REGISTRY: ghcr.io

jobs:
  build-git-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: rest-broadcaster
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Containerfile
          directory:  .
          addLatest: true
          tags: ${{ steps.checkout.outputs.new-tag }}